---
- name: Set yaml repo os_name
  set_fact:
    yum_os_distribution: 'openeuler'
    yum_os_version: '22.03'

- name: Include RedHat General Repo Init
  include_tasks: ctyunos-repo.yml

- name: Include RedHat Family Common Tasks
  include_tasks: redhat.yml
