- hosts: all
  any_errors_fatal: true
  roles:
    - utils/misc-check
    - utils/detect-os
    - common

- hosts: mariadb_node
  roles:
    - mariadb
  tags:
    - db

- hosts: mariadb_ha_nodes
  roles:
    - mariadb-ha

- hosts: clickhouse_node
  roles:
    - clickhouse/install
  tags:
    - db
    - clickhouse

- hosts: registry_node
  roles:
    - registry

- hosts: primary_master_node
  roles:
    - primary-master-node/setup_kubernetes
    - restore/add-sync-user

- hosts: master_nodes
  roles:
    - master-node
  tags:
    - k3s

- hosts: worker_nodes
  roles:
    - worker-node
  tags:
    - k3s

- hosts: primary_master_node:master_nodes:worker_nodes
  roles:
    - { role: utils/gpu-init, when: 'enable_containerd|default(false) == false' }
  tags:
    - gpu

- hosts: primary_master_node:master_nodes:worker_nodes
  roles:
    - { role: utils/containerd, when: 'enable_containerd|default(false) == true' }
  tags:
    - containerd

- hosts: master_nodes:worker_nodes
  roles:
    - { role: utils/kernel-check, when: 'enable_containerd|default(false) == false' }
  tags:
    - kernel

- hosts: primary_master_node
  roles:
    - primary-master-node/setup_cloud
    - utils/enable-eip
  tags:
    - cloud

- hosts: clickhouse_node
  roles:
    - clickhouse/deploy
  tags:
    - db
    - clickhouse

- hosts: worker_nodes
  roles:
    - utils/eip-ha
  tags:
    - eip

- hosts: primary_master_node:master_nodes
  roles:
    - utils/k8s/apiserver/args

- hosts: primary_master_node:master_nodes:worker_nodes
  roles:
    - primary-master-node/reboot
  tags:
    - reboot
